#185172080 Add a readme file and badges
atlp-rwanda/Team-Sostene-E-commerce-fe pull request #1
Opened 2023-05-16 12:49 UTC by AdrineUWERA

#### What does this PR do?

Adds a readme file with badges. 

#### Description of Task to be completed?

Add a detailed readme file for the API to include the information below:

- Installation and run commands
- Description
- Dependencies
- Tests setup and execution
- Add badges:
    Code Climate maintainability badge
    Code Climate code coverage badge
    CircleCI status badge

#### How should this be manually tested?

- Check the repo's readme

#### What are the relevant pivotal tracker/Trello stories?

#185172080

2023-05-16 13:13 UTC, Kress2000 approved these changes

2023-05-17 13:12 UTC, Edcreation approved these changes

2023-05-19 09:35 UTC, Edcreation requested changes

2023-05-19 09:35 UTC, Edcreation commented on .circleci/config.yml
> +
We are using yarn

2023-05-19 09:36 UTC, Kress2000 commented on README.md
> +npm run test
were are using yarn not npm

2023-05-19 09:38 UTC, Kress2000 requested changes
unless you changed the package.js and package-loc, we are using yarn plz! check there

2023-05-19 09:40 UTC, Edcreation approved these changes

2023-05-19 09:44 UTC, Kress2000 approved these changes
good, but I was suggesting to  add `yarn run dev --host` in the ### Getting started  section  for those who want to start the project on IP address. For this method you can even access it on your phone, it it will be good for us in development during responsiveness

2023-05-19 10:49 UTC, Pacific911 approved these changes

2023-05-19 12:13 UTC, munezerobagira approved these changes

2023-05-19 12:13 UTC, merged