#185172078 configure react router
atlp-rwanda/Team-Sostene-E-commerce-fe pull request #10
Opened 2023-05-19 10:42 UTC by Edcreation

#### What does this PR do?

#### Description of Task to be completed?
- Setup react router  (React-router-dom)
#### How should this be manually tested?
- By Reviewing codes you can identify react router being used
#### Any background context you want to provide?
- Set Up Agreed upon folder structure
#### What are the relevant pivotal tracker/Trello stories?
- 185172078

2023-05-19 15:02 UTC, Pacific911 approved these changes

2023-05-20 07:35 UTC, ishimwe5555 approved these changes
LG

2023-05-20 09:53 UTC, JosephNgabo approved these changes

2023-05-22 14:16 UTC, munezerobagira requested changes

2023-05-22 14:16 UTC, munezerobagira commented on jest.config.cjs
> +  testMatch: ['<rootDir>/src/**/*.test.(ts|tsx)', '<rootDir>/src/**/*.spec.(ts|tsx)'],
can you add collectCoverageFrom also

2023-05-22 14:16 UTC, munezerobagira commented on package.json
> +  "author": "AdrineUwera <a.uwera@alustudent.com>",
why did you add this line

2023-05-22 20:38 UTC, Edcreation commented on jest.config.cjs
> +  testMatch: ['<rootDir>/src/**/*.test.(ts|tsx)', '<rootDir>/src/**/*.spec.(ts|tsx)'],
Added!

2023-05-22 22:23 UTC, munezerobagira approved these changes

2023-05-22 22:23 UTC, merged