#185172079 Setup SASS processing
atlp-rwanda/Team-Sostene-E-commerce-fe pull request #15
Opened 2023-05-21 21:41 UTC by mirindi19

What does this PR do?
- Setup SASS processing on the client

Description of Task to be completed?
- Install and setup sass pre-processing on the application.

What are the relevant pivotal tracker/Trello stories?
#185172079

2023-05-21 21:49 UTC, Kress2000 requested changes
[Package-lock.json](https://github.com/atlp-rwanda/Team-Sostene-E-commerce-fe/pull/15/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519) shouldn't be here. means you have installed the sass packages using ``npm`` while you had to use only ``yarn``.

2023-05-22 13:25 UTC, munezerobagira approved these changes

2023-05-23 05:45 UTC, Kress2000 approved these changes
good work

2023-05-23 06:26 UTC, munezerobagira approved these changes

2023-05-23 06:28 UTC, merged