ft(about_us): designed the about us page for the ecommerce app
atlp-rwanda/Team-Sostene-E-commerce-fe pull request #24
Opened 2023-06-02 12:55 UTC by Pacific911

#### What does this PR do?

- Shows more about the e commerce website 
-  what the services they offer 
- Places and you can find them
- 
#### Description of Task to be completed?
- /about_us

#### Screenshots (if appropriate)

![screen shot](https://github.com/atlp-rwanda/Team-Sostene-E-commerce-fe/assets/58509941/455e1afc-75fc-49fe-baf2-33a4ca4877df)

2023-06-02 18:35 UTC, princoo commented on src/pages/accounts/Accounts.tsx
clean this line

2023-06-06 07:01 UTC, Pacific911 commented on src/pages/accounts/Accounts.tsx
solved 👍

2023-06-06 09:52 UTC, munezerobagira approved these changes

2023-06-06 10:07 UTC, AdrineUWERA approved these changes

2023-06-06 10:07 UTC, AdrineUWERA approved these changes

2023-06-06 10:12 UTC, princoo approved these changes

2023-06-06 10:12 UTC, Edcreation requested changes

2023-06-06 10:12 UTC, Edcreation commented on src/pages/about/about_us.tsx
> +  { name: 'Said MIRINDI', imageSrc: teamImages[6] },
Name

2023-06-06 10:35 UTC, JosephNgabo approved these changes

2023-06-06 10:41 UTC, Pacific911 commented on src/pages/about/about_us.tsx
> +  { name: 'Said MIRINDI', imageSrc: teamImages[6] },
requested changes made

2023-06-06 10:47 UTC, Edcreation approved these changes

2023-06-06 12:19 UTC, merged