#185172119 implement change password
atlp-rwanda/Team-Sostene-E-commerce-fe pull request #27
Opened 2023-06-05 01:26 UTC by princoo

#### What does this PR do?

-ensures a user changes the password to a new one
-ensure the new password is strong as the old one
- make sure the form is validated before making an API call

#### What are the relevant pivotal tracker/Trello stories?

#185172119

2023-06-07 08:42 UTC, Kress2000 commented on src/pages/editAccount/main.tsx
> +    const divElement = document.getElementsByClassName('change-password-error')[0];
this is not a good approach to work within React TSX, you have a virtual document already. use Redux or useState to get the value and put them inside the TSX elements there down., what if a class is changed?

2023-06-07 08:44 UTC, Kress2000 commented on src/pages/editAccount/main.tsx
> +            placeholder="OLD PASSWORD"
and here needs to be formik validations. user won't submit with fake or bad credentials

2023-06-07 08:45 UTC, Kress2000 commented on src/pages/home/home.tsx
> -import GoogleBtn from '../../components/googleLogin/button';
This btn was used to logIn with google I think. why removed it?

2023-06-07 08:46 UTC, Kress2000 requested changes
check some comments there

2023-06-07 10:21 UTC, munezerobagira commented on src/components/button/button.tsx
> +};
duplicate code from adrine PR

2023-06-07 10:22 UTC, munezerobagira commented on src/components/button/button.tsx
> +};
https://github.com/atlp-rwanda/Team-Sostene-E-commerce-fe/blob/125efc0ac9a5101e84bd4b296ef60b407d0e90eb/src/components/reusables/Reusable.tsx

2023-06-07 10:33 UTC, munezerobagira requested changes

2023-06-07 10:33 UTC, munezerobagira commented on src/components/input/input.tsx
> +};
check this one also

2023-06-07 10:33 UTC, munezerobagira commented on src/pages/home/home.tsx
> +      <Changepassword />
this can be moved from he   user profile drop down before logout

2023-06-08 15:32 UTC, Kress2000 approved these changes

2023-06-08 17:28 UTC, Edcreation approved these changes

2023-06-09 09:49 UTC, munezerobagira requested changes

2023-06-12 19:59 UTC, munezerobagira requested changes

2023-06-12 19:59 UTC, munezerobagira commented on src/pages/accounts/editAccount/changepass.tsx
> +
Display error below the text same here we can do it same here

2023-06-13 14:20 UTC, Pacific911 approved these changes

2023-06-13 17:42 UTC, JosephNgabo approved these changes

2023-06-14 07:06 UTC, munezerobagira approved these changes

2023-06-14 07:06 UTC, merged