feat(interface): implement a slideshow for the home page
atlp-rwanda/Team-Sostene-E-commerce-fe pull request #30
Opened 2023-06-06 06:25 UTC by AdrineUWERA

#### What does this PR do?

- Creates a slideshow that will be used for showcasing

#### Description of Task to be completed?

- Add a slideshow on the homepage

#### How should this be manually tested?

 - Run the application
 - View the slideshow on the landing page
 
#### Screenshots (if appropriate)

![image](https://github.com/atlp-rwanda/Team-Sostene-E-commerce-fe/assets/90565982/b52582c6-ec7a-4e89-978b-3160ae09a718)

2023-06-06 12:28 UTC, Edcreation approved these changes

2023-06-06 18:37 UTC, JosephNgabo approved these changes

2023-06-07 10:07 UTC, munezerobagira requested changes

2023-06-07 10:07 UTC, munezerobagira commented on src/pages/home/home.tsx
>        </div>
```suggestion

```

2023-06-07 14:42 UTC, merged