#185172101 A user should be able to chat with other user in the app
atlp-rwanda/Team-Sostene-E-commerce-fe pull request #33
Opened 2023-06-07 08:29 UTC by Kress2000

#### What does this PR do?
Enables the user to chat with others in the app when logged in.
#### Description of Task to be completed?
used socket.io

#### How should this be manually tested?
at `baseUrl/chatRoom` you are able to chat with others after login in

#### What are the relevant pivotal tracker/Trello stories?
#185172101

2023-06-19 08:48 UTC, AdrineUWERA requested changes
Use the color theme we chose for our website.

2023-06-25 17:27 UTC, JosephNgabo approved these changes

2023-06-26 06:27 UTC, Edcreation reviewed
Try to work more on the UI, that message box margins, border radius etc.

2023-06-26 17:33 UTC, mirindi19 approved these changes

2023-06-26 18:44 UTC, munezerobagira approved these changes

2023-06-26 19:02 UTC, AdrineUWERA approved these changes

2023-06-26 20:05 UTC, merged