#185172099 admin assigns roles(role based access control)
atlp-rwanda/Team-Sostene-E-commerce-fe pull request #39
Opened 2023-06-12 14:38 UTC by Edcreation

#### What does this PR do?
- Set Up Protection components to allow access to specified roles
-  added Admin page to assign roles
#### Description of Task to be completed?
RBAC(Role based access control) - Admin should be able to assign roles [customer,merchant,admin]
#### How should this be manually tested?
- Log In as ADMIN
- Go to account icon on navbar click manage users
- See list of users
- select role then click on check button to assign role
#### Any background context you want to provide?
- Admin can search through users
#### What are the relevant pivotal tracker/Trello stories?
185172099
#### Screenshots (if appropriate)
![Screenshot 2023-06-12 163634](https://github.com/atlp-rwanda/Team-Sostene-E-commerce-fe/assets/93517096/0da30983-5227-4a07-924d-81ffeaf6563b)

2023-06-13 11:58 UTC, AdrineUWERA approved these changes

2023-06-13 13:48 UTC, Kress2000 requested changes
use Hooks

2023-06-13 16:51 UTC, Edcreation commented on src/components/roles/Protected.tsx
> +  if (store.getState().token.value) {
what hook?

2023-06-15 13:44 UTC, Kress2000 approved these changes

2023-06-15 13:57 UTC, princoo approved these changes

2023-06-15 19:47 UTC, munezerobagira commented
closes #47

2023-06-16 10:39 UTC, munezerobagira approved these changes

2023-06-16 10:40 UTC, merged