ft(contact): created a contact page
atlp-rwanda/Team-Sostene-E-commerce-fe pull request #40
Opened 2023-06-12 15:38 UTC by Pacific911

#### What does this PR do?

- Contacting for more informations
- When a user want to add the feedback 

#### Screenshots (if appropriate)
![contact](https://github.com/atlp-rwanda/Team-Sostene-E-commerce-fe/assets/58509941/a3d043ac-bff8-41fc-b2e4-d406e9c5deed)

2023-06-13 10:28 UTC, Edcreation reviewed
NIce!. You can work more on page responsiveness

2023-06-13 11:28 UTC, AdrineUWERA requested changes
Test the components and do the story book.
Use the same font size for the titles on the contact page

2023-06-13 16:43 UTC, AdrineUWERA approved these changes

2023-06-13 16:46 UTC, Edcreation approved these changes

2023-06-13 17:41 UTC, JosephNgabo approved these changes

2023-06-14 09:43 UTC, princoo approved these changes

2023-06-14 13:33 UTC, munezerobagira approved these changes

2023-06-14 13:34 UTC, merged