#185172115 a buyer should track order status
atlp-rwanda/Team-Sostene-E-commerce-fe pull request #45
Opened 2023-06-14 14:16 UTC by Pacific911

#### What does this PR do?

  - A buyer should be to track the status of the orders 
  - A buyer should be to check the status of the product if it is confirmed or still pending

#### How should this be manually tested?
 - GET : /orders

#### What are the relevant pivotal tracker/Trello stories?
 - 185172115

#### Screenshots (if appropriate)

2023-06-21 15:14 UTC, JosephNgabo reviewed
try to resolve some conflicts available due to rebase

2023-06-23 01:07 UTC, princoo requested changes
on your page you need to provide an `element(button)` that redirects to the payment form
if the order is `not yet` payed successfully (does not have status `succeeded`).

2023-06-23 09:11 UTC, munezerobagira requested changes

2023-06-23 09:11 UTC, munezerobagira commented on src/pages/orders/redux/trackOrderSlice.tsx
> +// }
```suggestion
```

2023-06-23 09:11 UTC, munezerobagira commented on src/pages/orders/trackOrder.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
```suggestion
```

2023-06-26 13:46 UTC, Pacific911 commented on src/pages/orders/redux/trackOrderSlice.tsx
> +// }
done 👍

2023-06-26 13:46 UTC, Pacific911 commented on src/pages/orders/trackOrder.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
solved

2023-06-26 15:40 UTC, princoo reviewed
adjust the position of elements in this column

<img width="700" alt="order" src="https://github.com/atlp-rwanda/Team-Sostene-E-commerce-fe/assets/99591226/df586136-15c0-4fe6-afe9-5ca37c93f9f2">

2023-06-26 16:29 UTC, Edcreation approved these changes

2023-06-26 16:36 UTC, AdrineUWERA approved these changes

2023-06-26 16:55 UTC, munezerobagira approved these changes

2023-06-26 16:55 UTC, merged