# Fix home and other components
atlp-rwanda/Team-Sostene-E-commerce-fe pull request #48
Opened 2023-06-16 08:32 UTC by AdrineUWERA

#### What does this PR do?

- ensure that the home page looks appealing
- ensure that the contact page is responsive
- ensure that the seller items are not overlaping

#### Description of Task to be completed?

- Correct faults in some components

#### How should this be manually tested?

- Check the home page ('/' route)
- Check the contact page ('/contact' route)
- Check the seller items page ('/sellerItems' route)

2023-06-16 08:53 UTC, Pacific911 approved these changes

2023-06-16 10:23 UTC, munezerobagira requested changes
1. move this links, `Home`, `Contact us`, `About us ` from top nav to footer and interchange  it with search bar( with increase sized) but 'SIgnup link can remain'
<img width="417" alt="image" src="https://github.com/atlp-rwanda/Team-Sostene-E-commerce-fe/assets/42154315/424ad5e6-62fc-4a0e-84f8-827adee7f008">
2. Instead of having signup action when user is not logged in we can have login and we make sure that it primary button
<img width="148" alt="image" src="https://github.com/atlp-rwanda/Team-Sostene-E-commerce-fe/assets/42154315/1cdabcfa-e521-4df4-ab3c-fed785321e66">

2023-06-19 08:31 UTC, princoo approved these changes

2023-06-19 08:42 UTC, munezerobagira commented
<img width="351" alt="image" src="https://github.com/atlp-rwanda/Team-Sostene-E-commerce-fe/assets/42154315/55614b16-51e4-484d-9712-959da2d05e04">
This font is not looking good on safari

2023-06-19 08:57 UTC, Kress2000 requested changes
remember to make a logo wrapper in a link, that links a user to the home page bcz home page must be accessible to the user wherever is navigation bar, ---  otherwise, it is fine

2023-06-19 13:08 UTC, Edcreation approved these changes

2023-06-19 16:20 UTC, merged