#185172085 Configure storybook for component development
atlp-rwanda/Team-Sostene-E-commerce-fe pull request #5
Opened 2023-05-17 12:29 UTC by JosephNgabo

#### What does this PR do?
* creates storybook for using on related components
#### Description of Task to be completed?
* This PR allows the configuration of all features to use on storybook to allow the easy reusable of components
#### How should this be manually tested?
* After cloning the Repo user should create new storybook features and run them using `npm run storybook`
#### What are the relevant pivotal tracker/Trello stories?
#185172085

2023-05-27 08:06 UTC, munezerobagira requested changes
you can use naming of `Demo.storybook.tsx` instead of `Demo.stories.tsx`
then you can ignore coverage from any any file that has the format of *.storybook.{tsx|ts}

2023-05-27 08:41 UTC, JosephNgabo commented
> you can use naming of `Demo.storybook.tsx` instead of `Demo.stories.tsx` then you can ignore coverage from any any file that has the format of *.storybook.{tsx|ts}

resolved now

2023-05-27 11:06 UTC, Kress2000 requested changes
![image](https://github.com/atlp-rwanda/Team-Sostene-E-commerce-fe/assets/91186046/2f8ac9bc-11bc-45f5-89e0-8fb7f8dc2923)
I suggest you use stander structure such as that one  or any other you want but , do not mix project components with stories. 
I suggest you create stories folder under src, and putt all your stories there, and then it look like this probably : 
``src/components`` : for projects main components
``src/stories`` : here is your task to put those demo stories
``src/.. `` other folders such as ``hooks`` , ``redux`` ,  ``designComponents`` , etc

2023-05-27 11:31 UTC, Kress2000 approved these changes

2023-05-27 18:46 UTC, munezerobagira approved these changes

2023-05-28 17:47 UTC, Edcreation approved these changes

2023-05-28 20:03 UTC, merged