#185172108 A buyer is able to update his/her cart
atlp-rwanda/Team-Sostene-E-commerce-fe pull request #51
Opened 2023-06-18 18:57 UTC by Kress2000

#### What does this PR do?
Enables the buyer to update his cart as long as there are some products added there.

#### Description of Task to be completed?
  -ensure that if the users have logged in, they wil be able to update the cart, and reflect directly to its price and the total price as well -ensure that when you click on update button, you enter in edit mode, and the table is editable, and  when we click on finish btn, will turn edit mode off

#### How should this be manually tested?
At` /cart` route, you will be able to view cart items, with the update Btn, there you can click on Update Btn to edit number of products you want to buy, delete some of them you don't want, etc.

#### What are the relevant pivotal tracker/Trello stories?
#185172108

2023-06-20 06:31 UTC, Pacific911 requested changes

2023-06-20 06:31 UTC, Pacific911 commented on vite.config.ts.timestamp-1687124826014-e2a74658bea0b.mjs
> +//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsidml0ZS5jb25maWcudHMiXSwKICAic291cmNlc0NvbnRlbnQiOiBbImNvbnN0IF9fdml0ZV9pbmplY3RlZF9vcmlnaW5hbF9kaXJuYW1lI
what's this for ???? it's not necessary if your not using it

2023-06-21 23:32 UTC, ishimwe5555 approved these changes

2023-06-22 14:16 UTC, JosephNgabo reviewed
can you fix the responsiveness check how it is!

2023-06-22 14:47 UTC, Kress2000 commented on src/components/Product/Handler.tsx
> +              ?.slice(0, 10)
we were solving the issue with slice

2023-06-22 14:50 UTC, JosephNgabo approved these changes

2023-06-22 18:06 UTC, munezerobagira approved these changes

2023-06-22 18:06 UTC, merged