#185172114 buyer should be able to search for products
atlp-rwanda/Team-Sostene-E-commerce-fe pull request #52
Opened 2023-06-18 20:50 UTC by mirindi19

#### What does this PR do?
- The buyer should be shown a list of products that match the search criteria
- The buyer clicks on a product from the search results
-T he buyer should be taken to the product page where they can view all relevant details about the product including the description, image, and price

#### How should this be manually tested?
- Login first then go to search bar

#### What are the relevant pivotal tracker/Trello stories?
#185172114

2023-06-20 19:58 UTC, AdrineUWERA requested changes
Increase the width of the search bar and add some padding between the title and the cards, and align them as well.

![image](https://github.com/atlp-rwanda/Team-Sostene-E-commerce-fe/assets/90565982/e3a04ead-eddd-4ac9-97a9-4db41381fb46)

2023-06-22 06:51 UTC, Pacific911 requested changes
rebase first !!

2023-06-26 06:05 UTC, JosephNgabo approved these changes

2023-06-26 06:23 UTC, Edcreation approved these changes

2023-06-26 07:18 UTC, AdrineUWERA approved these changes

2023-06-26 12:50 UTC, munezerobagira approved these changes

2023-06-26 12:50 UTC, merged