Ft reviews ratings
atlp-rwanda/Team-Sostene-E-commerce-fe pull request #63
Opened 2023-06-26 11:33 UTC by JosephNgabo

#### What does this PR do?
Lets users to post the feedbacks and reviews on certain product
#### Description of Task to be completed?
after reveiwing single product their form that holds recent feedbacks added on product and can add anotheer new one.
#### How should this be manually tested?
by accessing the single product page
#### What are the relevant pivotal tracker/Trello stories?
#185172112
#### Screenshots (if appropriate)

2023-06-28 12:50 UTC, AdrineUWERA approved these changes

2023-06-28 12:50 UTC, AdrineUWERA commented on src/pages/feebdacks/tests/review.test.tsx
> +      // <MemoryRouter initialEntries={['/product/6ac24373-0bc0-414b-92d2-d78f8ada8878']}>
Remove the comments in this file.

2023-06-28 16:52 UTC, princoo approved these changes

2023-06-29 12:57 UTC, Pacific911 requested changes

2023-06-29 12:57 UTC, Pacific911 commented on src/pages/feebdacks/tests/review.test.tsx
> +      // <MemoryRouter initialEntries={['/product/6ac24373-0bc0-414b-92d2-d78f8ada8878']}>
you can remove these comments if not needed

2023-06-29 12:57 UTC, Pacific911 commented on src/pages/feebdacks/tests/review.test.tsx
> +      // </MemoryRouter>
and here too

2023-06-29 12:57 UTC, Pacific911 commented on src/pages/feebdacks/tests/review.test.tsx
> +        // expect(AddReview).toHaveBeenCalledWith(id);
check here

2023-06-29 12:57 UTC, Pacific911 commented on src/pages/feebdacks/tests/review.test.tsx
> +  // it('should dispatch reviews action correctly', async () => {
and on this entire file too if your not using them anywhere

2023-06-29 13:47 UTC, Pacific911 approved these changes

2023-06-29 16:45 UTC, munezerobagira approved these changes

2023-06-29 22:05 UTC, merged